include: package:lint/analysis_options.yaml

linter:
  rules:
    annotate_overrides: true
    prefer_interpolation_to_compose_strings: true
    unnecessary_new: true
    sort_child_properties_last: true
    unawaited_futures: true
    await_only_futures: true
    unnecessary_await_in_return: true
    sort_pub_dependencies: false

analyzer:
  exclude:
    - 'lib/locale_keys.g.dart'
  errors:
    annotate_overrides: warning
    prefer_interpolation_to_compose_strings: warning
    unnecessary_new: warning
    sort_child_properties_last: warning
    await_only_futures: warning
    unnecessary_await_in_return: warning