name: authentication
description: Mecar Demo
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # An opinionated, community-driven set of lint rules for Dart and Flutter projects. Like pedantic but stricter
  lint: ^1.10.0

  # Easy and Fast internationalizing and localization your Flutter Apps, this package simplify the internationalizing process .
  easy_localization: ^3.0.1

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # swiper/carousel for flutter, with multiple layouts, infinite loop. Compatible with Android & iOS.
  card_swiper: ^2.0.4

  # A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  equatable: ^2.0.3

  # Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern. Built to be used with the bloc state management package.
  flutter_bloc: ^8.0.1

  # The EasyRichText widget provides an easy way to use RichText. You do not have to split the string manually.
  easy_rich_text: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: SFUIText
      fonts:
        - asset: assets/fonts/SFUIText-Regular.ttf
        - asset: assets/fonts/SFUIText-Semibold.ttf
          weight: 600
  assets:
    - assets/langs/
    - assets/icons/
    - assets/images/